version: -1

records:
  - name: about
    type: about
    file: about.md
  - name: Main
    cathegory: main
    type: main
  - name: Prediction power
    time: 2014-11-01
    cathegory: Machine Learning
    file: prediction_power.md
    img: https://boardgamegeek.com/camo/29aca422fcb5d61fca521f9c6c95c1a9ea427691/687474703a2f2f32352e6d656469612e74756d626c722e636f6d2f74756d626c725f6d356b71633675437a4f317279756f64366f315f313238302e6a7067
    tags: 
      - Machine Learning
      - Probability
      - Math
  - name: Onus probandi
    time: 2014-11-15
    cathegory: Comprehension
    img: /img/shked.jpg
    file: onus_probandi.md
    tags:
      - Proof
      - Skepticism
      - Falsifiability
  - name: Kolmogorov complexity
    time: 2014-11-25
    cathegory: Machine Learning
    file: kolmogorov.md
    tags:
      - Machine Learning
      - Probability
      - Math
  - name: lex parsimoniae 
    time: 2014-12-12
    cathegory: Comprehension
    img: http://knife.kasumi.ru/upload/medialibrary/13b/britva1.jpg
    file: okkama.md
    tags:
      - Math
      - Probability
      - Skepticism
  - name: Heap paradox solvation
    time: 2014-12-25
    cathegory: Comprehension
    file: heap_paradox.md
    tags:
      - Proof
